#security:
#  oauth2:
#    client:
#      clientId: 945810355774596
#      clientSecret: 90485b7792e62792d94108de84d3ebf4
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

facebook:
  client:
    clientId: 945810355774596
    clientSecret: 90485b7792e62792d94108de84d3ebf4
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

jsf:
  primefaces:
    theme: mytheme